package:
  name: coffee
  version: {{ environ.get('GIT_DESCRIBE_TAG','') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - networkx

  run:
    - python
    - numpy
    - networkx

test:
  requires:
    - pytest
    - flake8
  commands:
    - py.test {{ os.path.join(environ.get('SRC_DIR'), 'tests') }} -v
    - flake8 {{ environ.get('SRC_DIR') }}

about:
  home: http://www.firedrakeproject.org
  license: BSD 3-clause
  summary: COFFEE - COmpiler For Fast Expression Evaluation
